version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    ports:
      - 127.0.0.1:8067:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - swtxl-wp:/var/www/html/
      - ./swing-tx-left-theme/:/var/www/html/wp-content/themes/swing-tx-left-theme

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
volumes:
  swtxl-wp: